### ISSUE TITLE
Create weekly batch job that dumps all domains and their IP addresses

### ISSUE THREAD

**Issue by h701h** [canada-ca/tracker#4520] opened 2023-05-12 17:30 UTC
Automate the process of creating a report that lists all domains and their IP addresses. 

- [ ] Make sure the report is available for download by an admin. 
- [ ] Include if the org is under the PGS

**Comment by lcampbell2** [comment] 2024-07-17 19:17
adding IPs to the export CSV will achieve this on demand. Closing this as a duplicate of #5424

**Closed by lcampbell2** 2024-07-17 19:17 UTC
